server.port=${PORT:8080}
# Production Datasource
spring.datasource.url=jdbc:${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

eureka.client.service-url.defaultZone=${EUREKA_URL}
