server.port=${PORT:8080}
# Production Datasource
spring.datasource.url=jdbc:postgresql://${DB_HOST}/${DB_NAME}?sslmode=require
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

eureka.client.service-url.defaultZone=${EUREKA_URL}
