spring.application.name=user-service
spring.profiles.active=prod


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database=postgresql

eureka.instance.hostname=${EUREKA_HOSTNAME}
eureka.instance.ip-address=${EUREKA_IP}
eureka.instance.prefer-ip-address=${EUREKA_PREFER_IP}


server.netty.connection-timeout=30000
spring.mvc.async.request-timeout=30000
