spring.application.name=user-service
spring.profiles.active=dev


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

eureka.instance.hostname=localhost
eureka.instance.ip-address=127.0.0.1
eureka.instance.prefer-ip-address=false

server.netty.connection-timeout=30000
spring.mvc.async.request-timeout=30000
